# Generated by Django 5.0.1 on 2024-02-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rail_ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='acPrice',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='train',
            name='sleeperPrice',
            field=models.BigIntegerField(default=0),
        ),
    ]
